name: CI

on: push
 
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Run format checks
        id: format
        run: dotnet format Game.sln --no-restore --verify-no-changes --verbosity detailed #need to specify, if you want the sln or csproj, sine they are on the same level

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  

      - name: Run tests
        id: test
        run: dotnet test --verbosity normal 
